# Generated by Django 2.2.1 on 2019-05-04 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videochannel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='likes',
            name='like',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
