# Generated by Django 2.2.1 on 2019-05-04 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videochannel', '0002_auto_20190504_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='likes',
            name='like',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
