# Generated by Django 2.2.1 on 2019-05-04 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videochannel', '0004_auto_20190504_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='likes',
            name='like',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
