# Generated by Django 2.2.1 on 2019-05-04 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videochannel', '0005_auto_20190504_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(blank=True, max_length=500, null=True, unique=True),
        ),
    ]
