# Generated by Django 2.2.1 on 2019-05-04 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videochannel', '0006_auto_20190504_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='comments',
            field=models.ManyToManyField(null=True, to='videochannel.Comment'),
        ),
        migrations.AlterField(
            model_name='video',
            name='likes',
            field=models.ManyToManyField(null=True, related_name='likes', to='videochannel.Likes'),
        ),
    ]
