# Generated by Django 2.2.1 on 2019-05-04 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videochannel', '0008_auto_20190504_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(default='', max_length=500),
        ),
    ]
