# Generated by Django 2.2.1 on 2019-05-04 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videochannel', '0009_auto_20190504_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='like',
            field=models.PositiveIntegerField(),
        ),
    ]
