# Generated by Django 2.2.1 on 2019-05-15 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videochannel', '0010_auto_20190504_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='likes',
            field=models.ManyToManyField(blank=True, default=0, null=True, related_name='likes', to='videochannel.Likes'),
        ),
    ]
