# Generated by Django 2.2.1 on 2019-05-15 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videochannel', '0011_auto_20190515_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='like',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
