# Generated by Django 2.2.1 on 2019-05-15 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videochannel', '0012_auto_20190515_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='like',
            field=models.PositiveIntegerField(),
        ),
    ]
