# Generated by Django 2.2.1 on 2019-05-15 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videochannel', '0016_auto_20190515_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
