# Generated by Django 2.2.1 on 2019-06-26 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videochannel', '0018_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='like',
        ),
    ]
