# Generated by Django 2.2.1 on 2019-07-22 15:37

from django.db import migrations, models
import videochannel.models


class Migration(migrations.Migration):

    dependencies = [
        ('videochannel', '0019_remove_likes_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='likescounts',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name=videochannel.models.Likes),
        ),
    ]
