# Generated by Django 2.2.1 on 2019-07-22 15:45

from django.db import migrations, models
import videochannel.models


class Migration(migrations.Migration):

    dependencies = [
        ('videochannel', '0021_remove_video_likescounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='likescounts',
            field=models.PositiveIntegerField(default=0, verbose_name=videochannel.models.Likes),
        ),
    ]
