# Generated by Django 2.2.1 on 2019-07-22 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videochannel', '0022_video_likescounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='likescounts',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
